---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunath
  labels:
    app: bunath
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bunath
  template:
    metadata:
      labels:
        app: bunath
    spec:
      containers:
        - name: bunath
          image: docker.io/phengbunath/bunath:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080